### PR TITLE
fixed test and possible ConfigureEnvironment bug

### PR DESCRIPTION
**Pull request by memsharded**
CI of the PR was broken:
- Fixed broken test
- Adjusted pep8 column limit (100 chars)
- The MOST IMPORTANT: **fixed bug** in ConfigureEnvironment cpp_flags. The first value of `cpp_flags` was overwritten, so the values of `-s -NDEBUG` **were lost**. This of course can affect the packages, not being really release versions. I think it is not a very big deal, as `ConfigureEnvironment` is mostly used in C projects, thus cppflags not used, but I would like @lasote to have a look and track this issue too.

### CODE REVIEW

**Comment by tru** [comment]
Interesting. Thanks for the fixes. I will re-issue the PR later today.

Btw I don't think we should hardcode -s in ConfigureEnv since its not valid for at least clang on OSX. It should probably be in some kind of compiler specific config somewhere.

**Comment by memsharded** [comment]
Yes, that is true, I have found in the log of: https://travis-ci.org/lasote/conan-zlib/jobs/136887900

That it is being ignored. I guess it could be conditionally added then. Not a big issue, though, it seems the compiler discarding it without problem, maybe add a "strip" apple-clang equivalent? Deserves an issue?

**Comment by memsharded** [comment]
Hi Tobias,

Do you think that we should address the -s issue here in this PR, or maybe better just merge it to update the conan PR and ensure it gets to 0.10, and open a new issue for it? Thanjs!

**Comment by tru** [comment]
Included this, the PR against conan/conan should be updated now.

**Pull request closed without merging**
